### ISSUE TITLE
try out PRANK with the tree used for simulation

### ISSUE THREAD

**Issue by matsen** [cswarth/hiv-sim#10]

**Comment by cswarth** [comment]
This issue is about using the actual tree from which the simulated samples were selected as a guide tree for PRANK.  This would provide the most advantageous situation for PRANK to infer the founder sequence.   We could also compare the actual distribution of indel events on branches to the actual events used to produce the sequences.

From the limited santa documentation,
### Sampling genealogies: 

&lt;tree&gt;

 ###

In addition to sampling sequences, the genealogies that gave rise to
those samples may also be sampled.  For example, the configuration below
produces a NEXUS format ancestral tree for 10 random viruses selected
from the population every 100 generations.

As with the `<alignment>` sampler, a random subset of viruses is
selected from the population
each time the sampler is run.  It is possible to get a complete
picture of the branching process if the tree sample size matches the
population size.  The resulting trees may be viewed with
[figtree](http://tree.bio.ed.ac.uk/software/figtree/) or
other tree visualization software.

```
    <sampler>
        <atFrequency>100</atFrequency>
        <fileName>santa_out.trees</fileName>
        <tree>
   	    <sampleSize>10</sampleSize>
   	    <format>NEXUS</format>
   	    <label>sequence_%s</label>
        </tree>
    </sampler>
```

**Comment by cswarth** [comment]
The problem with this is that we combine samples from both donor and recipient lineages when inferring an ancestral founder.   The recipient sample is rooted at a single sample taken from the donor, and it is easy to extract the genealogy.
The donor sample, however, may not bear any direct relationship to the sequence used to found the recipient lineage.   The founder of the recipient lineage may have died out in the donor lineage before the donor was sampled.  Even if descendants survive in the donor population, there is no guarantee that one of those descendants will be in the sample taken from the donor.

How does one come up with a "true" tree then?

**Comment by cswarth** [comment]
Discussed the issue w/ Erick.  The actual solution for creating a tree that aggregates data from both donor and recipient lineage sounds complicated.  We decided to punt on this for now and instead focus on letting prank infer its own guide tree.

**Comment by cswarth** [comment]
Closed as per previous comment
