### ISSUE TITLE
Add consensus sequence as a method

### ISSUE THREAD

**Issue by matsen** [cswarth/hiv-sim#5]
This will allow us to compare to the McCloskey results (at least more than we are currently able to do).

**Comment by cswarth** [comment]
Calculated consensus of donor+recipient samples using  `Bio.Align.AlignInfo.SummaryInfo.gap_consensus()` which seems to call a base if it has at least 75% prevalence, and leaves it 'X' otherwise.

![plot-plot scores by method](https://cloud.githubusercontent.com/assets/295428/7438378/168f42ba-f018-11e4-8dc4-2e97aaecf3a8.png)

**Comment by matsen** [comment]
Totally cool! Here's what the McCloskey paper has to say:

![image](https://cloud.githubusercontent.com/assets/112708/7438572/45fa0974-f01b-11e4-975c-906c7e7624c8.png)

so it sounds like they are taking the most common base as the consensus, and only X if it's an exact tie between the top two contenders. Even simpler than what I think you are doing, but I'm not sure if it's implemented in BioPy exactly.

**Comment by cswarth** [comment]
I have implemented the consensus as described in the, McCloskey paper, but it turns out this is in fact a much more complicated consensus calculation, not simpler.
It's easy to calculate a plurality consensus, but this method also has special treatment for ties.  That means we don't simply calculate the maximum, we have to keep track of **all** the maximum values at each site.   And then resolution of the tie depends on the tied residues at that site; any gap yields '?', 'X' otherwise.
